// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plotengine} from '../models';
import {foreshadow} from '../models';
import {models} from '../models';
import {setting} from '../models';
import {typo} from '../models';
import {config} from '../models';
import {coordinator} from '../models';
import {character} from '../models';
import {style} from '../models';

export function AnalyseBranch(arg1:plotengine.Branch):Promise<plotengine.BranchAnalysis>;

export function AnalyzeStyle(arg1:string,arg2:string):Promise<string>;

export function AutoDetectForeshadowing(arg1:string):Promise<Array<foreshadow.CandidateForeshadow>>;

export function ConfirmForeshadowing(arg1:foreshadow.CandidateForeshadow,arg2:string):Promise<string>;

export function CreateChapter(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateCharacter(arg1:models.Character):Promise<string>;

export function CreateVolume(arg1:string):Promise<string>;

export function DeleteChapter(arg1:string):Promise<void>;

export function DeleteCharacter(arg1:string):Promise<void>;

export function DeleteForeshadowing(arg1:string):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function DeleteStyleProfile(arg1:string):Promise<void>;

export function DeleteVolume(arg1:string):Promise<void>;

export function DetectSettings(arg1:string,arg2:boolean,arg3:boolean):Promise<Array<setting.SettingHit>>;

export function DetectTypos(arg1:string):Promise<Array<typo.TypoSuggestion>>;

export function GenerateBranches(arg1:plotengine.GenerationParams):Promise<Array<plotengine.Branch>>;

export function GenerateDialogue(arg1:string,arg2:string):Promise<string>;

export function GenerateHealthReport():Promise<foreshadow.HealthReport>;

export function GetAssistantIntensity():Promise<number>;

export function GetChapter(arg1:string):Promise<models.Chapter>;

export function GetCharacter(arg1:string):Promise<models.Character>;

export function GetConfig():Promise<config.Config>;

export function GetEmbedderEngine():Promise<string>;

export function GetForeshadowing(arg1:string):Promise<models.Foreshadowing>;

export function GetSessionHistory():Promise<Array<coordinator.SessionEvent>>;

export function GetSetting(arg1:string):Promise<models.WorldSetting>;

export function GetStyleProfile(arg1:string):Promise<models.StyleProfile>;

export function ImportContent(arg1:string,arg2:string):Promise<Array<string>>;

export function ImportDocument(arg1:string):Promise<Array<string>>;

export function LearnStyle(arg1:string,arg2:Array<string>):Promise<string>;

export function ListChapters():Promise<Array<models.ChapterSummary>>;

export function ListCharacters():Promise<Array<character.CharacterSummary>>;

export function ListForeshadowings(arg1:string):Promise<Array<foreshadow.ForeshadowSummary>>;

export function ListSettings():Promise<Array<setting.SettingInfo>>;

export function ListStyleProfiles():Promise<Array<style.StyleProfileSummary>>;

export function ListVolumes():Promise<Array<models.VolumeSummary>>;

export function MergeBranches(arg1:Array<string>):Promise<string>;

export function OnParagraphWritten(arg1:string,arg2:string):Promise<void>;

export function PolishText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RecordNotificationAction(arg1:string,arg2:string):Promise<void>;

export function ReorderChapters(arg1:Array<string>):Promise<void>;

export function ReviseDialogue(arg1:string,arg2:string):Promise<string>;

export function SaveForeshadowing(arg1:string,arg2:string):Promise<string>;

export function SelectExeFile():Promise<string>;

export function SelectGGUFFile():Promise<string>;

export function SetAssistantIntensity(arg1:number):Promise<void>;

export function SuggestReveal(arg1:number):Promise<Array<foreshadow.RevealSuggestion>>;

export function TestEmbeddingConnection(arg1:string,arg2:string):Promise<void>;

export function TestEmbeddingLocal():Promise<string>;

export function TestLLMConnection(arg1:string,arg2:string):Promise<void>;

export function UpdateChapter(arg1:string,arg2:string):Promise<void>;

export function UpdateChapterTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateChapterVolume(arg1:string,arg2:string):Promise<void>;

export function UpdateCharacter(arg1:string,arg2:models.Character):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateForeshadowing(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateVolume(arg1:string,arg2:string):Promise<void>;

export function UploadWorldSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateSetting(arg1:string,arg2:string):Promise<setting.ConflictResult>;
