// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyseBranch(arg1) {
  return window['go']['main']['App']['AnalyseBranch'](arg1);
}

export function AnalyzeStyle(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeStyle'](arg1, arg2);
}

export function AutoDetectForeshadowing(arg1) {
  return window['go']['main']['App']['AutoDetectForeshadowing'](arg1);
}

export function ConfirmForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['ConfirmForeshadowing'](arg1, arg2);
}

export function CreateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2, arg3);
}

export function CreateCharacter(arg1) {
  return window['go']['main']['App']['CreateCharacter'](arg1);
}

export function CreateVolume(arg1) {
  return window['go']['main']['App']['CreateVolume'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteForeshadowing(arg1) {
  return window['go']['main']['App']['DeleteForeshadowing'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['main']['App']['DeleteSetting'](arg1);
}

export function DeleteStyleProfile(arg1) {
  return window['go']['main']['App']['DeleteStyleProfile'](arg1);
}

export function DeleteVolume(arg1) {
  return window['go']['main']['App']['DeleteVolume'](arg1);
}

export function DetectSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectSettings'](arg1, arg2, arg3);
}

export function DetectTypos(arg1) {
  return window['go']['main']['App']['DetectTypos'](arg1);
}

export function GenerateBranches(arg1) {
  return window['go']['main']['App']['GenerateBranches'](arg1);
}

export function GenerateDialogue(arg1, arg2) {
  return window['go']['main']['App']['GenerateDialogue'](arg1, arg2);
}

export function GenerateHealthReport() {
  return window['go']['main']['App']['GenerateHealthReport']();
}

export function GetAssistantIntensity() {
  return window['go']['main']['App']['GetAssistantIntensity']();
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEmbedderEngine() {
  return window['go']['main']['App']['GetEmbedderEngine']();
}

export function GetForeshadowing(arg1) {
  return window['go']['main']['App']['GetForeshadowing'](arg1);
}

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetStyleProfile(arg1) {
  return window['go']['main']['App']['GetStyleProfile'](arg1);
}

export function ImportContent(arg1, arg2) {
  return window['go']['main']['App']['ImportContent'](arg1, arg2);
}

export function ImportDocument(arg1) {
  return window['go']['main']['App']['ImportDocument'](arg1);
}

export function LearnStyle(arg1, arg2) {
  return window['go']['main']['App']['LearnStyle'](arg1, arg2);
}

export function ListChapters() {
  return window['go']['main']['App']['ListChapters']();
}

export function ListCharacters() {
  return window['go']['main']['App']['ListCharacters']();
}

export function ListForeshadowings(arg1) {
  return window['go']['main']['App']['ListForeshadowings'](arg1);
}

export function ListSettings() {
  return window['go']['main']['App']['ListSettings']();
}

export function ListStyleProfiles() {
  return window['go']['main']['App']['ListStyleProfiles']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function MergeBranches(arg1) {
  return window['go']['main']['App']['MergeBranches'](arg1);
}

export function OnParagraphWritten(arg1, arg2) {
  return window['go']['main']['App']['OnParagraphWritten'](arg1, arg2);
}

export function PolishText(arg1, arg2, arg3) {
  return window['go']['main']['App']['PolishText'](arg1, arg2, arg3);
}

export function RecordNotificationAction(arg1, arg2) {
  return window['go']['main']['App']['RecordNotificationAction'](arg1, arg2);
}

export function ReorderChapters(arg1) {
  return window['go']['main']['App']['ReorderChapters'](arg1);
}

export function ReviseDialogue(arg1, arg2) {
  return window['go']['main']['App']['ReviseDialogue'](arg1, arg2);
}

export function SaveForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['SaveForeshadowing'](arg1, arg2);
}

export function SelectExeFile() {
  return window['go']['main']['App']['SelectExeFile']();
}

export function SelectGGUFFile() {
  return window['go']['main']['App']['SelectGGUFFile']();
}

export function SetAssistantIntensity(arg1) {
  return window['go']['main']['App']['SetAssistantIntensity'](arg1);
}

export function SuggestReveal(arg1) {
  return window['go']['main']['App']['SuggestReveal'](arg1);
}

export function TestEmbeddingConnection(arg1, arg2) {
  return window['go']['main']['App']['TestEmbeddingConnection'](arg1, arg2);
}

export function TestEmbeddingLocal() {
  return window['go']['main']['App']['TestEmbeddingLocal']();
}

export function TestLLMConnection(arg1, arg2) {
  return window['go']['main']['App']['TestLLMConnection'](arg1, arg2);
}

export function UpdateChapter(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2);
}

export function UpdateChapterTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapterTitle'](arg1, arg2);
}

export function UpdateChapterVolume(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapterVolume'](arg1, arg2);
}

export function UpdateCharacter(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharacter'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['UpdateForeshadowing'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3, arg4);
}

export function UpdateVolume(arg1, arg2) {
  return window['go']['main']['App']['UpdateVolume'](arg1, arg2);
}

export function UploadWorldSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadWorldSetting'](arg1, arg2, arg3);
}

export function ValidateSetting(arg1, arg2) {
  return window['go']['main']['App']['ValidateSetting'](arg1, arg2);
}
