// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyseBranch(arg1) {
  return window['go']['main']['App']['AnalyseBranch'](arg1);
}

export function AutoDetectForeshadowing(arg1) {
  return window['go']['main']['App']['AutoDetectForeshadowing'](arg1);
}

export function BindOutlineChapter(arg1, arg2) {
  return window['go']['main']['App']['BindOutlineChapter'](arg1, arg2);
}

export function ConfirmForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['ConfirmForeshadowing'](arg1, arg2);
}

export function CreateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2, arg3);
}

export function CreateCharacter(arg1) {
  return window['go']['main']['App']['CreateCharacter'](arg1);
}

export function CreateOutlineNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateOutlineNode'](arg1, arg2, arg3);
}

export function CreateRelationship(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRelationship'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTimelineEvent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateTimelineEvent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateTimelineNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTimelineNode'](arg1, arg2, arg3);
}

export function CreateVolume(arg1) {
  return window['go']['main']['App']['CreateVolume'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteForeshadowing(arg1) {
  return window['go']['main']['App']['DeleteForeshadowing'](arg1);
}

export function DeleteOutlineNode(arg1) {
  return window['go']['main']['App']['DeleteOutlineNode'](arg1);
}

export function DeleteRelationship(arg1) {
  return window['go']['main']['App']['DeleteRelationship'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['main']['App']['DeleteSetting'](arg1);
}

export function DeleteTimelineEvent(arg1) {
  return window['go']['main']['App']['DeleteTimelineEvent'](arg1);
}

export function DeleteTimelineNode(arg1) {
  return window['go']['main']['App']['DeleteTimelineNode'](arg1);
}

export function DeleteVolume(arg1) {
  return window['go']['main']['App']['DeleteVolume'](arg1);
}

export function DetectSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectSettings'](arg1, arg2, arg3);
}

export function DetectTypos(arg1) {
  return window['go']['main']['App']['DetectTypos'](arg1);
}

export function ExportOutlineMarkdown() {
  return window['go']['main']['App']['ExportOutlineMarkdown']();
}

export function ExportStatsCSV() {
  return window['go']['main']['App']['ExportStatsCSV']();
}

export function GenerateBranches(arg1) {
  return window['go']['main']['App']['GenerateBranches'](arg1);
}

export function GenerateDialogue(arg1, arg2) {
  return window['go']['main']['App']['GenerateDialogue'](arg1, arg2);
}

export function GenerateHealthReport() {
  return window['go']['main']['App']['GenerateHealthReport']();
}

export function GetAssistantIntensity() {
  return window['go']['main']['App']['GetAssistantIntensity']();
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEmbedderEngine() {
  return window['go']['main']['App']['GetEmbedderEngine']();
}

export function GetForeshadowing(arg1) {
  return window['go']['main']['App']['GetForeshadowing'](arg1);
}

export function GetOutlineNodeByChapter(arg1) {
  return window['go']['main']['App']['GetOutlineNodeByChapter'](arg1);
}

export function GetOutlineTree() {
  return window['go']['main']['App']['GetOutlineTree']();
}

export function GetRelationshipGraph(arg1) {
  return window['go']['main']['App']['GetRelationshipGraph'](arg1);
}

export function GetRelationships(arg1) {
  return window['go']['main']['App']['GetRelationships'](arg1);
}

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetTimeBase() {
  return window['go']['main']['App']['GetTimeBase']();
}

export function GetTimelineNode(arg1) {
  return window['go']['main']['App']['GetTimelineNode'](arg1);
}

export function GetTodayWritingStats() {
  return window['go']['main']['App']['GetTodayWritingStats']();
}

export function GetWeekWritingStats() {
  return window['go']['main']['App']['GetWeekWritingStats']();
}

export function GetWritingGoals() {
  return window['go']['main']['App']['GetWritingGoals']();
}

export function GetWritingStats(arg1) {
  return window['go']['main']['App']['GetWritingStats'](arg1);
}

export function GetWritingStats365() {
  return window['go']['main']['App']['GetWritingStats365']();
}

export function GetWritingStreak() {
  return window['go']['main']['App']['GetWritingStreak']();
}

export function ImportContent(arg1, arg2) {
  return window['go']['main']['App']['ImportContent'](arg1, arg2);
}

export function ImportDocument(arg1) {
  return window['go']['main']['App']['ImportDocument'](arg1);
}

export function ImportOutlineFromChapters() {
  return window['go']['main']['App']['ImportOutlineFromChapters']();
}

export function ListChapters() {
  return window['go']['main']['App']['ListChapters']();
}

export function ListCharacters() {
  return window['go']['main']['App']['ListCharacters']();
}

export function ListForeshadowings(arg1) {
  return window['go']['main']['App']['ListForeshadowings'](arg1);
}

export function ListSettings() {
  return window['go']['main']['App']['ListSettings']();
}

export function ListTimelineNodes() {
  return window['go']['main']['App']['ListTimelineNodes']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function MergeBranches(arg1) {
  return window['go']['main']['App']['MergeBranches'](arg1);
}

export function MoveOutlineNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveOutlineNode'](arg1, arg2, arg3);
}

export function OnParagraphWritten(arg1, arg2) {
  return window['go']['main']['App']['OnParagraphWritten'](arg1, arg2);
}

export function PolishWithInstruction(arg1, arg2, arg3) {
  return window['go']['main']['App']['PolishWithInstruction'](arg1, arg2, arg3);
}

export function RecordNotificationAction(arg1, arg2) {
  return window['go']['main']['App']['RecordNotificationAction'](arg1, arg2);
}

export function ReorderChapters(arg1) {
  return window['go']['main']['App']['ReorderChapters'](arg1);
}

export function ReplaceInChapters(arg1, arg2) {
  return window['go']['main']['App']['ReplaceInChapters'](arg1, arg2);
}

export function ReviseDialogue(arg1, arg2) {
  return window['go']['main']['App']['ReviseDialogue'](arg1, arg2);
}

export function SaveForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['SaveForeshadowing'](arg1, arg2);
}

export function SaveGraphPositions(arg1) {
  return window['go']['main']['App']['SaveGraphPositions'](arg1);
}

export function SaveTimeBase(arg1, arg2) {
  return window['go']['main']['App']['SaveTimeBase'](arg1, arg2);
}

export function ScanChaptersForTimeline(arg1) {
  return window['go']['main']['App']['ScanChaptersForTimeline'](arg1);
}

export function SearchChapters(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchChapters'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectExeFile() {
  return window['go']['main']['App']['SelectExeFile']();
}

export function SelectGGUFFile() {
  return window['go']['main']['App']['SelectGGUFFile']();
}

export function SetAssistantIntensity(arg1) {
  return window['go']['main']['App']['SetAssistantIntensity'](arg1);
}

export function SetWritingGoals(arg1, arg2) {
  return window['go']['main']['App']['SetWritingGoals'](arg1, arg2);
}

export function SuggestReveal(arg1) {
  return window['go']['main']['App']['SuggestReveal'](arg1);
}

export function TestEmbeddingConnection(arg1, arg2) {
  return window['go']['main']['App']['TestEmbeddingConnection'](arg1, arg2);
}

export function TestEmbeddingLocal() {
  return window['go']['main']['App']['TestEmbeddingLocal']();
}

export function TestLLMConnection(arg1, arg2) {
  return window['go']['main']['App']['TestLLMConnection'](arg1, arg2);
}

export function UnbindOutlineChapter(arg1) {
  return window['go']['main']['App']['UnbindOutlineChapter'](arg1);
}

export function UpdateChapter(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2);
}

export function UpdateChapterTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapterTitle'](arg1, arg2);
}

export function UpdateChapterVolume(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapterVolume'](arg1, arg2);
}

export function UpdateCharacter(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharacter'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateForeshadowing(arg1, arg2) {
  return window['go']['main']['App']['UpdateForeshadowing'](arg1, arg2);
}

export function UpdateOutlineNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateOutlineNode'](arg1, arg2, arg3, arg4);
}

export function UpdateRelationship(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRelationship'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3, arg4);
}

export function UpdateTimelineEvent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTimelineEvent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTimelineNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTimelineNode'](arg1, arg2, arg3, arg4);
}

export function UpdateVolume(arg1, arg2) {
  return window['go']['main']['App']['UpdateVolume'](arg1, arg2);
}

export function UpdateWritingGoalSettings(arg1) {
  return window['go']['main']['App']['UpdateWritingGoalSettings'](arg1);
}

export function UploadWorldSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadWorldSetting'](arg1, arg2, arg3);
}

export function ValidateSetting(arg1, arg2) {
  return window['go']['main']['App']['ValidateSetting'](arg1, arg2);
}
